### ISSUE TITLE
Plans with multiple buckets

### ISSUE THREAD

**Issue by kamil4** [felixb/callmeter#99]
I'm having difficulty conveying the pricing structure of my operator to Call Meter.

The operator is Tracfone USA, a prepaid. They use three buckets, separate for calls, text (SMS and MMS) and data.  So, e.g., a $20 refill card adds 180 minutes, 180 texts, and 180 MB. This seems to trigger two issues with the Call Meter:

Under Advanced Preferences I selected a Prepaid Plan, and added two more billing periods to keep track of each bucket separately. That seems to work, but in the "Now" view under the first billing period Call Meter displays the sum of all three of them (540 rather than the expected 180) and the names of the billing periods are not displayed anywhere which is confusing (see the attached screenshot).

The second issue is that Call Meter seems to be coded around the concept of the balance always being a cash value. But in my case the balance is simply the number of minutes/texts/MBs. So I set the individual costs of each call/SMS/MMS to "1" and set the custom currency symbol to " " (a space) to get rid of the dollar sign. That seems to work, but as you can see in the screenshot, it looks kind-of ugly (the cumulative "cost" displayed under each item is redundant and just clutters the display).

I wonder if there is already a better way to do what I want? Would I be better off using limits instead?

![screenshot_2015-12-23-15-19-56](https://cloud.githubusercontent.com/assets/16415200/11978424/2a24c7b2-a951-11e5-852b-db7992a1204c.png)

**Comment by felixb** [comment]
This is kind of complicated setup. It might be model your plans rules in the app correctly. Prepaid plans are only supported half the way.

You can try adding a forth bill period for your calls bucket and keep the first one as sum.
You might switch to mixed plans for messages or calls to get a units instead of message count and billed minutes. The bill periods do not support anything but cost, though.
